### ISSUE TITLE
File Not Found error on native mobile

### ISSUE THREAD

**Issue by Capital75** [JelteMX/mendix-file-dropper#12] opened 2020-07-15 12:23 UTC
Hi Jelte,
The filedropper is a wonderful widget! It works on all devices, as long as the web-version is used.
Once downloaded as part of a hybrid app, the filedropper can't seem to find the right file-path, resulting in the error 'FileDropper.js?637298182946539990:1 POST file:///file?guid=160159261748365372 net::ERR_FILE_NOT_FOUND'

**Comment by florisdg** [comment] 2020-08-20 08:23
Exactly the same error with a hybrid mobile app. However only through the iOS and Android applicatoins. When you open our webapp in a browser on either OS the widget actually works. Which is odd to me because both mobile apps are basically a webview. I played with giving the app permissoins to my Files and Storage on Android but still got the same error. Currently about to start inspecting this widget's source code to find a fix. If I manage to fix it i'll report back here.

**Comment by florisdg** [comment] 2020-09-11 10:08
@Capital75 this issue ticket can be closed as this issue is caused by mendix/hybrid-app-template/issues/39 🐙

**Closed** 2020-09-21 08:59 UTC
